version: '2.0'

services:

  mysql:
    container_name: shared-mysql
    # https://community.home-assistant.io/t/mariadb-errors-after-update/424731
    # after upgrade run: make upgrade
    image: mariadb:11.1.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    mem_limit: 600m
    networks:
      - default
      - external_default

# docker network create external_default
networks:
    external_default:
      external: true

#    network_mode: bridge

#    deploy:
#    resources:
#      limits:
#        memory: 400M
